[package]
name = "ldtk_easy"
version = "0.1.0"
edition = "2021"
description = "An easy to use LDTK library."
license = "MIT or Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ldtk_deser_json = "0.1.2"